on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      
name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.8.1' # Optional, use a specific version of Flutter
        working-directory: FlutterAppMain/
      - run: flutter pub get
        working-directory: FlutterAppMain/
      - name: Analyze Dart
        uses: zgosalvez/github-actions-analyze-dart@v1
        working-directory: FlutterAppMain/
      - run: flutter build apk --debug --split-per-abi --no-sound-null-safety
        working-directory: FlutterAppMain/
      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/debug/*"
          tag: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        working-directory: FlutterAppMain/
